### ISSUE TITLE
three master setup

### ISSUE THREAD

**Issue by mattma** [mattma/coreos-distro#3]
Update the `README.md` and `etcd-user-data` with three master setup instruction.

One master node works as expected. Three master node does not work.

Question 1: When all three machines loads up with `etcd-user-data` file as cloud-init setting, they both load with the static value `listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001`. See [here](https://github.com/mattma/coreos-distro/blob/master/etcd-user-data#L10). 

When I follow the current README doc, in the first master, I got 

```
coreos-01 core # etcdctl   cluster-health
cluster is healthy
member 6ae27f9fa2984b1d is healthy
```

But it did not detect the 2nd master. Even though I have the setting (Have done `daemon-reload` on both machine after setting the new value in `initial-cluster.conf`)

```
# /etc/systemd/system/etcd2.service.d/initial-cluster.conf
[Service]
Environment="ETCD_INITIAL_CLUSTER=784767c97ce5410f931f0cfee19523f8=http://172.17.8.101:2380,c1f07ef72ede4399b9fc35d14e5db0a8=http://172.17.9.101:2380"
```

In the 2nd machine, follow the same step in One master node with the setting above in `initial-cluster.conf`. So in this case, both master one and master two have the exactly same value in `/etc/systemd/system/etcd2.service.d/initial-cluster.conf`. 

Master two `etcd` is running as fine. But when got error below when run 

```
node-01 core # etcdctl cluster-health
Error:  cannot sync with the cluster using endpoints http://127.0.0.1:4001, http://127.0.0.1:2379
```

I believe there must be the static value issue in cloud-init file, may need to be updated as well.

Another question, If I set the environment variable of `ROLE`. E.G:  ROLE=master with `vagrant up` will load up `etcd-user-data`.  And ROLE=node will load up `user-data`. This is the legacy stuff, right? It will always gonna load `etcd-user-data` in this case?????

**Comment by yichengq** [comment]
To static bootstrap, all etcd members should use brand-new data directory. If it detects the data dir, it will ignore the -initial flags and start based on data dir. I think that's why you cannot set it up.

> This is the legacy stuff, right? It will always gonna load etcd-user-data in this case?????

i don't quite understand. all master should load `etcd-user-data` and set `ETCD_INITIAL_CLUSTER` after start.

**Comment by mattma** [comment]
Thanks.  I will check it this weekend!

**Comment by mattma** [comment]
@yichengq 

The latest commit have introduced a new feature. When you run `vagrant up`, it will automatically start the `etcd2.service` in the `master` node. I have built-in a shell script at `setup/etcd-start` to echo the README instruction. 

I may need to discuss with you on 3 masters setup and write it in a script file too. How to form a etcd cluster

**Comment by mattma** [comment]
> i don't quite understand. all master should load etcd-user-data and set ETCD_INITIAL_CLUSTER after start.

I was confused with 3 master setup and One master + peers setup. After playing around, we just need to have a single master etcd master with several peer nodes for now.
